#!/usr/bin/env bash
# https://medium.com/kinandcartacreated/githooks-explained-using-flutter-babcdeb4048d
printf "\n#### Running the Flutter analyzer ############\n\n"
fvm flutter format .
printf "#### Finished the Flutter analyzer #############\n\n"

fvm flutter analyze
if [ $? -ne 0 ]; then
  printf "\n############################################"
  printf "\n#### Flutter analyzer error ↑ #############"
  printf "\n############################################" 
  exit 1
fi
printf "\n#### Finished running the Flutter analyzer ###"