include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - 'test/*.dart'
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'firebase_options.dart'
  errors:
    invalid_annotation_target: ignore
