include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - 'test/*.dart'
  # errors:
  #   todo: ignore
  #   invalid_annotation_target: ignore
  #   flutter_style_todos: ignore
